// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250505173240_FixClientNavigationProperties")]
    partial class FixClientNavigationProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VCT.API.Models.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("VCT.API.Models.Clients.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("VCT.API.Models.Components.Canal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("CanalHeight")
                        .HasColumnType("real");

                    b.Property<int>("CanalNumber")
                        .HasColumnType("int");

                    b.Property<float>("CanalWidth")
                        .HasColumnType("real");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("ExtractorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrayId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ExtractorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TrayId");

                    b.ToTable("Canals");
                });

            modelBuilder.Entity("VCT.API.Models.Components.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("VCT.API.Models.Components.Extractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtractorType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Extractor");

                    b.HasDiscriminator<string>("ExtractorType").HasValue("Extractor");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VCT.API.Models.Components.Tray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Trays");
                });

            modelBuilder.Entity("VCT.API.Models.Machines.MasterMachine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ConfigId")
                        .HasColumnType("int");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ConfigId");

                    b.ToTable("MasterMachines");
                });

            modelBuilder.Entity("VCT.API.Models.Machines.SatelliteMachine", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("ConfigId")
                        .HasColumnType("int");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("int");

                    b.Property<int?>("MasterMachineid")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("MasterMachineid");

                    b.ToTable("SatelliteMachine");
                });

            modelBuilder.Entity("VCT.API.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<float>("Depth")
                        .HasColumnType("real");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stable")
                        .HasColumnType("bit");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ClientId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("VCT.API.Models.Components.HighExtractor", b =>
                {
                    b.HasBaseType("VCT.API.Models.Components.Extractor");

                    b.Property<int>("ClipDistance")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("High");
                });

            modelBuilder.Entity("VCT.API.Models.Components.LowExtractor", b =>
                {
                    b.HasBaseType("VCT.API.Models.Components.Extractor");

                    b.HasDiscriminator().HasValue("Low");
                });

            modelBuilder.Entity("VCT.API.Models.Clients.Client", b =>
                {
                    b.HasOne("VCT.API.Models.Accounts.Account", null)
                        .WithMany("Clients")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VCT.API.Models.Components.Canal", b =>
                {
                    b.HasOne("VCT.API.Models.Components.Extractor", "Extractor")
                        .WithMany()
                        .HasForeignKey("ExtractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VCT.API.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VCT.API.Models.Components.Tray", null)
                        .WithMany("Canals")
                        .HasForeignKey("TrayId");

                    b.Navigation("Extractor");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VCT.API.Models.Components.Tray", b =>
                {
                    b.HasOne("VCT.API.Models.Components.Configuration", null)
                        .WithMany("Trays")
                        .HasForeignKey("ConfigurationId");
                });

            modelBuilder.Entity("VCT.API.Models.Machines.MasterMachine", b =>
                {
                    b.HasOne("VCT.API.Models.Clients.Client", null)
                        .WithMany("Machines")
                        .HasForeignKey("ClientId");

                    b.HasOne("VCT.API.Models.Components.Configuration", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("VCT.API.Models.Machines.SatelliteMachine", b =>
                {
                    b.HasOne("VCT.API.Models.Components.Configuration", "Config")
                        .WithMany()
                        .HasForeignKey("ConfigId");

                    b.HasOne("VCT.API.Models.Machines.MasterMachine", null)
                        .WithMany("SatelliteMachines")
                        .HasForeignKey("MasterMachineid");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("VCT.API.Models.Products.Product", b =>
                {
                    b.HasOne("VCT.API.Models.Accounts.Account", null)
                        .WithMany("Products")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VCT.API.Models.Clients.Client", null)
                        .WithMany("Products")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("VCT.API.Models.Accounts.Account", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("VCT.API.Models.Clients.Client", b =>
                {
                    b.Navigation("Machines");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("VCT.API.Models.Components.Configuration", b =>
                {
                    b.Navigation("Trays");
                });

            modelBuilder.Entity("VCT.API.Models.Components.Tray", b =>
                {
                    b.Navigation("Canals");
                });

            modelBuilder.Entity("VCT.API.Models.Machines.MasterMachine", b =>
                {
                    b.Navigation("SatelliteMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
